site_name: My Docs
pages:
    - Home: index.md
    - About: about.md
    - Projects: projects.md
    - Kai: kai.md
    - Gerald: gerald.md
    - Smitha: smitha.md
    - Gerd: gerd.md
theme: readthedocs
